GET http://localhost:3000/accounts

###
GET http://localhost:3000/accounts/9cc86b2c-1705-41c2-ae09-211ab47ee10c

###
POST http://localhost:3000/accounts
Content-Type: application/json

{
  "name": "igor"
}

###
PATCH  http://localhost:3000/accounts/8a3ce573-5282-4042-b60c-3fbd3539eb0d
Content-Type: application/json

{
  "igor": "gregori"
}

###
DELETE  http://localhost:3000/accounts/8a3ce573-5282-4042-b60c-3fbd3539eb0d
