GET http://localhost:3000/orders
x-token: viand5508g

###
GET http://localhost:3000/orders/caae515b-0d8d-4097-b7ec-df0c1ddab3d9
x-token: viand5508g

###
POST http://localhost:3000/orders
Content-Type: application/json
x-token: viand5508g

{
  "amount": 130.00,
  "credit_card_number": "5244263055248800",
  "credit_card_name": "MARIA JOAQUINA",
  "credit_card_expiration_month": 12,
  "credit_card_expiration_year": 2022,
  "credit_card_cvv": "123"
}

###
PATCH  http://localhost:3000/orders/8a3ce573-5282-4042-b60c-3fbd3539eb0d
Content-Type: application/json

{
  "amount": 50.00,
  "credit_card_number": "4321"
}

###
DELETE  http://localhost:3000/orders/8a3ce573-5282-4042-b60c-3fbd3539eb0d
